configMapGenerator:
- files:
  - application.yml
  name: 82275303-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: cepgstapacr.azurecr.io/82275303
- name: cepgstapacr.azurecr.io/cloud-sample
  newTag: "202410250757"
